---
title: "The Command Line Interface"
format:
  html:
    toc: true
    toc-location: left
    self-contained: true
---

The command line -- the black box of unimaginable terror -- contains nearly every tool that your computer needs. I'll surface this now -- the Mac command line is far superior to the Windows command prompt. There is an endless supply of commands that you can use to do very basic things; think of anything that would require some mouse clicks of your computer and there is a CLI tool for doing it. While there is a ton of power there, I want to focus on a few things: basic navigation, running scripts, and text editors! 

## Basic Navigation 

If we want to move around on our computer, we use `cd`. 

To see all of the things in a folder, we use `ls` on Mac and `dir` on Windows

## Running Scripts

Let's just grab the basic dash example and we will work from there:

```{python, eval = FALSE}
from dash import Dash, html, dcc, callback, Output, Input
import plotly.express as px
import pandas as pd

df = pd.read_csv(
  'https://raw.githubusercontent.com/plotly/datasets/master/gapminder_unfiltered.csv'
)

app = Dash()

app.layout = [
    html.H1(children='Title of Dash App', style={'textAlign':'center'}),
    dcc.Dropdown(df.country.unique(), 'Canada', id='dropdown-selection'),
    dcc.Graph(id='graph-content')
]

@callback(
    Output('graph-content', 'figure'),
    Input('dropdown-selection', 'value')
)

def update_graph(value):
    dff = df[df.country==value]
    return px.line(dff, x='year', y='pop')

if __name__ == '__main__':
    app.run(debug=True)
```

We will call this file, `app.py`. 

## Text Editors

Prepare for pain and frustration! In one way, shape, or form, command lines have tools for editing text. You might be asking why you would ever need to do this; after all, you have a perfectly good IDE for writing code! While true, many systems that contain your files will not give you access to an IDE and you might need to hit your files with a quick edit. Using a command line editor becomes an awesomely efficient way to test files. 

If you are using a Windows machine and have Git installed (you should have Git installed), you can do the following:

```
"C:\Program Files\Git\usr\bin\vim.exe" app.py
```

On a Mac, you can just do this:

```
vim app.py
```

Whichever one you use, there are a few things to keep in mind:

```
i - insert mode
ESC - leave insert mode
yy - yank line (copy)
p - put line
dd - delete line
:w - write
:q - quite
:wq - write and quit
```

:::{.callout-note}
Vim -- Vi Improved -- is absolutely bonkers. It was made for programmers, by programmers, before the mouse became a thing. It will make you feel bad about yourself and question your abilities. If you want more info on what it can do, check out this link: https://docs.oracle.com/cd/E19455-01/806-2902/6jc3b36ee/index.html
:::

We will also need the following line:

```{python}
wb.open('http://127.0.0.1:8050/')
```

Let's test some places to drop that line and run our script.

## Running Scripts -- Revisited

Once we are into the CRC, we are going to make a directory for our code:

```
mkdir model_predictions
```

Now we can navigate to it:

```
cd model_predictions
```

Now, let's take the following code:

```{python}
#| echo: false

from joblib import load
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import accuracy_score, roc_auc_score, balanced_accuracy_score, matthews_corrcoef

X_train_scaled, X_test_scaled, y_train, y_test = load(
  'C:/Users/sberry5/Documents/teaching/level-up-python-data-modeling-and-model-evaluation-metrics-2499737/data/model_data.joblib'
  )

model_list = dict([
  ('logistic', linear_model.LogisticRegression(penalty='none')), 
  ('ridge', linear_model.LogisticRegressionCV(penalty='l2', solver='lbfgs')), 
  ('lasso', linear_model.LogisticRegressionCV(penalty='l1', solver='liblinear')), 
  ('elastic', linear_model.LogisticRegressionCV(penalty='elasticnet', l1_ratios = [.1, .5, .7, .9, .95, .99, 1], solver='saga'))
])
  
result = []

for i in list(model_list.keys()):
  model_name = i
  
  regression = model_list.get(i)

  regression.fit(X_train_scaled, y_train)
  
  print(regression.coef_)

  pred = regression.predict(X_test_scaled)
  
  accuracy = accuracy_score(y_test, pred)

  auc = roc_auc_score(y_test, regression.predict_proba(X_test_scaled)[:, 1])
  
  bas = balanced_accuracy_score(y_test, pred)
  
  mcc = matthews_corrcoef(y_test, pred)
  
  result_data = pd.DataFrame({'model': [model_name], 
  'accuracy': [accuracy],
  'auc': [auc], 
  'bas': bas, 
  'mcc': mcc})
  
  result.append(result_data)

pd.concat(result)
```

And run:

```
touch make_predictions.py
```

And then:

```
vim make_predictions.py
```


Now we can go into paste mode:

```
ESC
:set paste
i
SHIFT + INS
```

You'll now be able to navigate over the file with `h`, `j`, `k`, and `l`.

For now, though, let's just write and quit that file:

```
:wq
```

We need to move our model into our directory now, which is where the program that we are using become helpful!

Finally, we need to use the appropriate path within our code!

Now we can deal with getting python going! 

We have some libraries to install:

```
module load python

pip3 install --user imblearn pandas scikit-learn joblib
```

The hard work is done, so now we can create a bash script to submit our job!

We will touch a file:

```
touch prediction_job.script
```

And paste in the following:

```
#!/bin/bash
#$ -M sberry5@nd.edu    # Email address for job notification
#$ -m abe               # Send mail when job begins, ends and aborts
#$ -q long              # Specify queue
#$ -pe smp 1            # Specify number of cores to use.
#$ -N predictions       # Specify job name

module load python

python3 make_predictions.py
```

Now, we can submit our job:

```
qsub prediction_job.script
```
